
-- create
CREATE TABLE CLASSMATES (
  empId INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  age TEXT NOT NULL,
  address TEXT NOT NULL
);

-- insert
INSERT INTO CLASSMATES VALUES (0001, 'Clark', '22','Moscow');
INSERT INTO CLASSMATES VALUES (0002, 'Dave', '21', 'SPB');
INSERT INTO CLASSMATES VALUES (0003, 'Ava', '20', 'Moscow');
INSERT INTO CLASSMATES VALUES (0004, 'Eva', '24', 'Sochi');
INSERT INTO CLASSMATES VALUES (0005, 'Jake', '27', 'Anapa');

-- fetch 
SELECT name FROM CLASSMATES WHERE address = 'Moscow'AND age BETWEEN 18 AND 30;